In [110]:
import pandas as pd
import numpy as np

In [111]:
df_weather = pd.read_csv('filse/weather.csv')
df_weather

            Date  Temperature     Humidity    UV
0     2020-01-01    22.263951    44.616978   5.0
1     2020-01-02    30.703189    65.348507   3.0
2     2020-01-03    27.407223          NaN   7.0
3     2020-01-04          NaN -9999.000000   8.0
4     2020-01-05    26.367288 -9999.000000   6.0
...          ...          ...          ...   ...
4995  2033-09-04    18.851148    52.871657  10.0
4996  2033-09-05    28.624412    70.133370   9.0
4997  2033-09-06    31.401225    46.601295   3.0
4998  2033-09-07    22.743855    72.886503   2.0
4999  2033-09-08    23.672058    56.773185   9.0

[5000 rows x 4 columns]

In [112]:
df_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         5000 non-null   object
 1   Temperature  4712 non-null   float64
 2   Humidity     4712 non-null   float64
 3   UV           4808 non-null   float64
dtypes: float64(3), object(1)
memory usage: 156.4+ KB

In [113]:
df_weather.replace(9999, np.nan, inplace=True)
df_weather.replace(-9999, np.nan, inplace=True)

In [114]:
df_weather[df_weather.isnull().any(axis=1)]

            Date  Temperature   Humidity   UV
2     2020-01-03    27.407223        NaN  7.0
3     2020-01-04          NaN        NaN  8.0
4     2020-01-05    26.367288        NaN  6.0
8     2020-01-09    26.841193  60.999964  NaN
15    2020-01-16    17.159121        NaN  7.0
...          ...          ...        ...  ...
4976  2033-08-16          NaN  63.885942  1.0
4978  2033-08-18    26.320149        NaN  4.0
4981  2033-08-21    10.149057        NaN  5.0
4988  2033-08-28          NaN  62.046668  2.0
4990  2033-08-30          NaN  53.324299  4.0

[1197 rows x 4 columns]

In [115]:
df_weather.isnull().sum()

Date             0
Temperature    488
Humidity       488
UV             342
dtype: int64

In [116]:
df_weather.dropna(subset=["UV"], inplace=True)

In [123]:
df_weather.isnull().sum()

Date           0
Temperature    0
Humidity       0
UV             0
dtype: int64

In [ ]:
# df_weather.Temperature[df_weather.Temperature.isnull()] = df_weather.Temperature.mean()
df_weather.Temperature.fillna(df_weather.Temperature.mean(), inplace=True)

C:\Users\isaac\AppData\Local\Temp\ipykernel_2624\3742935250.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_weather.Temperature.fillna(df_weather.Temperature.mean(), inplace=True)

In [119]:
df_weather

            Date  Temperature   Humidity    UV
0     2020-01-01    22.263951  44.616978   5.0
1     2020-01-02    30.703189  65.348507   3.0
2     2020-01-03    27.407223        NaN   7.0
3     2020-01-04    25.089748        NaN   8.0
4     2020-01-05    26.367288        NaN   6.0
...          ...          ...        ...   ...
4995  2033-09-04    18.851148  52.871657  10.0
4996  2033-09-05    28.624412  70.133370   9.0
4997  2033-09-06    31.401225  46.601295   3.0
4998  2033-09-07    22.743855  72.886503   2.0
4999  2033-09-08    23.672058  56.773185   9.0

[4658 rows x 4 columns]

In [120]:
df_weather[df_weather.UV.isnull()]

Empty DataFrame
Columns: [Date, Temperature, Humidity, UV]
Index: []

In [122]:
df_weather.Humidity.ffill(inplace=True)

C:\Users\isaac\AppData\Local\Temp\ipykernel_2624\3169280529.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_weather.Humidity.ffill(inplace=True)

In [124]:
df_weather

            Date  Temperature   Humidity    UV
0     2020-01-01    22.263951  44.616978   5.0
1     2020-01-02    30.703189  65.348507   3.0
2     2020-01-03    27.407223  65.348507   7.0
3     2020-01-04    25.089748  65.348507   8.0
4     2020-01-05    26.367288  65.348507   6.0
...          ...          ...        ...   ...
4995  2033-09-04    18.851148  52.871657  10.0
4996  2033-09-05    28.624412  70.133370   9.0
4997  2033-09-06    31.401225  46.601295   3.0
4998  2033-09-07    22.743855  72.886503   2.0
4999  2033-09-08    23.672058  56.773185   9.0

[4658 rows x 4 columns]